name: Take Screenshot of dapetri.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Take Screenshot
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('https://dapetri.com');
            await page.screenshot({ path: 'dapetri-screenshot.png' });
            await browser.close();
          })();
          "
          mkdir .assets
          mv dapetri-screenshot.png .assets

      - name: Commit preview image to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .assets/dapetri-screenshot.png
          git commit -m "Add PNG preview image"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}